repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        # Enable auto-fix locally for convenience
        args: ["--fix"]
      - id: ruff-format
        # Enable auto-formatting
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic>=2
          - types-requests
          - boto3-stubs
        files: "^(src/|utils/|infra/|lambda/|main.py)"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
