# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blank_detect.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "blank_detect.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x62lank_detect.proto"6\n\x12\x42lankDetectMessage\x12\x10\n\x08\x65xpected\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tual\x18\x02 \x01(\t"9\n\x06\x42lanks\x12\r\n\x05value\x18\x01 \x01(\t\x12\x11\n\talignment\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2:\n\x0b\x42lankDetect\x12+\n\x0b\x62lankdetect\x12\x13.BlankDetectMessage\x1a\x07.Blanksb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "blank_detect_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_BLANKDETECTMESSAGE"]._serialized_start = 22
    _globals["_BLANKDETECTMESSAGE"]._serialized_end = 76
    _globals["_BLANKS"]._serialized_start = 78
    _globals["_BLANKS"]._serialized_end = 135
    _globals["_BLANKDETECT"]._serialized_start = 137
    _globals["_BLANKDETECT"]._serialized_end = 195
# @@protoc_insertion_point(module_scope)
